DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE users
(
    id       SERIAL PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    surname  VARCHAR(255) NOT NULL,
    type     VARCHAR(255) NOT NULL,
    status   VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE category
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE news
(
    id             SERIAL PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    content        TEXT,
    datetime       DATE,
    visits INTEGER,
    author_id      INTEGER,
    category_id    INTEGER,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE
);

CREATE TABLE comment
(
    id          SERIAL PRIMARY KEY,
    content     TEXT,
    datetime    DATE,
    author_id   INTEGER NOT NULL,
    news_id     INTEGER NOT NULL ,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
);

CREATE TABLE tag
(
    id   SERIAL PRIMARY KEY,
    text VARCHAR(255) NOT NULL
);

CREATE TABLE news_tag
(
    news_id INTEGER,
    tag_id  INTEGER,
    PRIMARY KEY (news_id, tag_id),
    FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);

INSERT INTO users (email, name, surname, type, status, password)
VALUES ('admin@admin.com', 'Admin', 'Adminovski', 'ADMIN', 'ACTIVE',
        'NHC/Gza4UcGDtJsELQ2dPLqdCXWdZOeiWtWuJPXO+DNQRthlUzzR5slZj+7uYuBK'),
       ('john@doe.com', 'John', 'Doe', 'ADMIN', 'ACTIVE',
        'lAOD8OzYGI9OmE99LY1tVOZeBphhtlKDs5ztLIEIjB7U0RwjNvB5mKJ+I3/f4eOM'),
       ('jane@smith.com', 'Jane', 'Smith', 'CONTENT_CREATOR', 'ACTIVE',
        '3/5R9mACmLYn+b97Vu6OfryB8jRZOt18+Uwc0eR4y5BzPQ5vt8S4sIaG+TWyQ9fK'),
       ('alice@johnson.com', 'Alice', 'Johnson', 'CONTENT_CREATOR', 'INACTIVE',
        'NX3hqzWfi8skPvxDWUiYQIGABA4680UhSD+lIDg8rw3/X5YT+SycGhtfFy41hSdK'),
       ('bob@anderson.com', 'Bob', 'Anderson', 'CONTENT_CREATOR', 'ACTIVE',
        '7YBjT31EJIVUsS2XU0wsmx8FbAfJbdYBM3AztCzTldz8xI4w8MOHPTQRgG8Snt0z'),
       ('charlie@brown.com', 'Charlie', 'Brown', 'CONTENT_CREATOR', 'ACTIVE',
        '+3YmVaeCW3fCtQU5howTvYdTrSd73lC4AlqFs3qRbUllO4bV//Cz82tE0FbI3Emh'),
       ('diana@wilson.com', 'Diana', 'Wilson', 'CONTENT_CREATOR', 'INACTIVE',
        'bj+iD/9Uu+BWXo8urrBhJsqQJofXgG1EFvwAqV+eYdK6BBryVF1HPq7gPXDHBsZp'),
       ('edward@rodriguez.com', 'Edward', 'Rodriguez', 'CONTENT_CREATOR', 'ACTIVE',
        'WofgotnIugMqi4zM9iDFLLycm7dJbgFj6VH0e6pKfkUA2loLsKuQTxzhnGm6kZc/'),
       ('fiona@miller.com', 'Fiona', 'Miller', 'CONTENT_CREATOR', 'INACTIVE',
        'M5aH/cy1OxT5WrqakDSHeia4QUkKVpm3c/WtW+3q6kTopqMj2CvIkvARpYm8j7Dl'),
       ('george@thompson.com', 'George', 'Thompson', 'CONTENT_CREATOR', 'ACTIVE',
        'MEwjuS9PEBh2BBwtU6/AK0a2zuo5SxKVNrXriaP8/2dlZ+aXpsheXtUEiYKfIK2t'),
       ('hannah@lewis.com', 'Hannah', 'Lewis', 'CONTENT_CREATOR', 'INACTIVE',
        'lkg80gaIGVuDM5NuUesELXEqmURmuIHaS/SBFugJrPgwwPvjwseRKyrhMZHBrT2X'),
       ('ian@hall.com', 'Ian', 'Hall', 'CONTENT_CREATOR', 'ACTIVE',
        '	glNLZvWeK+R9hkgNX2qf97ntnpvmaBIWCPUWGWzpEBHZrq+nrZx2la92qkptny0G'),
       ('jessica@lee.com', 'Jessica', 'Lee', 'CONTENT_CREATOR', 'INACTIVE',
        '4DTPk4Pr1ZL0cRaNhvi2icyd+Av8MLP+O6kVdtEmoTptctxuHY3mbA3sxnkYQRaM'),
       ('kevin@young.com', 'Kevin', 'Young', 'CONTENT_CREATOR', 'ACTIVE',
        'ge2NxHSz5s37ssL6f6mP8staCIaXve78ctdz0jDpATal/uyXA0Q67xnVnM1gLmvW'),
       ('linda@adams.com', 'Linda', 'Adams', 'CONTENT_CREATOR', 'INACTIVE',
        'HwjT0jdA7z+VbVdhSDYf1GcOFn+jvl33QTnfq8Ae27iYcueMe1gnDymbqR/jy7iB'),
       ('michael@harris.com', 'Michael', 'Harris', 'CONTENT_CREATOR', 'ACTIVE',
        'vIjGNlcp2d+8SMRZ7kjMS8U7Bo5MUT0C13Ghh31h36rqK8ZWD6fYJcK66rFHMPBe'),
       ('natalie@carter.com', 'Natalie', 'Carter', 'CONTENT_CREATOR', 'INACTIVE',
        'upnENm+pwf0PR95KzDNWjdjG/ppf4QnbOrkFEXrm72flW6efwYDn30VNu+Nxowbf'),
       ('oliver@wright.com', 'Oliver', 'Wright', 'CONTENT_CREATOR', 'ACTIVE',
        'TrGe7aiLfU7cumIuBa6WNCwB8LNjIEtrQz204vh5VVZDNb25pVDWIB+6n3DjoRyk'),
       ('pamela@green.com', 'Pamela', 'Green', 'CONTENT_CREATOR', 'INACTIVE',
        'zINVzlQxsOppk0o5SQ5wv1Hw2YAv7UAirdWjnfTglN9djPr6vrOzuc5BAOGtaWGC'),
       ('quincy@turner.com', 'Quincy', 'Turner', 'CONTENT_CREATOR', 'ACTIVE',
        'kwA1H9yiRoaOUfFqnleF6MWlBD41VkBxtVi4yxoQWshgchPt7FU+aoTjZiShZnuM'),
       ('rachel@bell.com', 'Rachel', 'Bell', 'CONTENT_CREATOR', 'INACTIVE',
        'aHfvhh7WgAiis9eXbIRIdCZf7LJc8RrdUEk46RspwgIJCrhl0Fris3+NARwRyThE'),
       ('steven@morris.com', 'Steven', 'Morris', 'CONTENT_CREATOR', 'ACTIVE',
        '61Q7pk792eBY87BUKEHno50IfBPS5SBraNX7Pf7ZMkWGGfsiGvVWRhr8IjWolPrX'),
       ('tina@scott.com', 'Tina', 'Scott', 'CONTENT_CREATOR', 'INACTIVE',
        'obtvMliPZMTHzZq1OAdkgdjhwdpay4UhgfSZQsKm3ZgYQ6P7hB/yAn9aQxKDWpfy'),
       ('victor@hughes.com', 'Victor', 'Hughes', 'CONTENT_CREATOR', 'ACTIVE',
        'mJOli0K37sSJWlREPRid0fCHzLUf3A3wd11khOywF8p3pHtZSXPsSqDnGPL00Wbz'),
       ('wendy@ross.com', 'Wendy', 'Ross', 'CONTENT_CREATOR', 'INACTIVE',
        'LODU0Oatm64B9qFUCd0Oqr1uGozyFg0qwPjC96pLLxURIZFRF+ZD8GGd76/AO0A/'),
       ('xavier@baker.com', 'Xavier', 'Baker', 'CONTENT_CREATOR', 'ACTIVE',
        '	ZX25keRjoisp1evRXh+TCEZ1EunGN9570F+xSIC/4XaQ6T2P8a0H3XqYjYRdpnCU'),
       ('yvonne@murray.com', 'Yvonne', 'Murray', 'CONTENT_CREATOR', 'INACTIVE',
        'gmOOpedemveka8f7PsXztFLohm3QqSpE6I+eseXqH000udBbFD6jZYDB0pMh+mL3'),
       ('zachary@nelson.com', 'Zachary', 'Nelson', 'CONTENT_CREATOR', 'ACTIVE',
        '3U8ofhYiOmtLRDqJ6pHaXkgZ5XSuSArQp9M6FNAqVbV8O2VkmFzez1dIgqvqmQtt');

INSERT INTO category (name, description)
VALUES ('Sports', 'News about sports events and athletes'),
       ('Politics', 'News related to political affairs'),
       ('Entertainment', 'News about movies, music, and celebrities'),
       ('Technology', 'News on the latest technological advancements'),
       ('Business', 'News related to the business world and economy'),
       ('Health', 'News and information on health and wellness'),
       ('Science', 'News about scientific discoveries and research'),
       ('Education', 'News and updates from the field of education'),
       ('Environment', 'News related to the environment and conservation'),
       ('Travel', 'News and insights on travel and destinations');

INSERT INTO news (title, content, datetime, visits, author_id, category_id)
VALUES ('Article 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra maecenas accumsan lacus vel facilisis volutpat est. Eros donec ac odio tempor orci dapibus. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Quam elementum pulvinar etiam non quam. Faucibus et molestie ac feugiat sed lectus. Quis hendrerit dolor magna eget est. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Cursus risus at ultrices mi. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Senectus et netus et malesuada fames ac turpis egestas.

Pharetra sit amet aliquam id diam maecenas ultricies. Et netus et malesuada fames. Scelerisque purus semper eget duis at tellus at. Cursus eget nunc scelerisque viverra mauris in aliquam. Non arcu risus quis varius quam quisque id. Vestibulum sed arcu non odio euismod lacinia. Tortor at auctor urna nunc id cursus. Ridiculus mus mauris vitae ultricies leo integer malesuada. Vitae aliquet nec ullamcorper sit amet risus. Tristique nulla aliquet enim tortor. Sed pulvinar proin gravida hendrerit lectus a. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Sapien faucibus et molestie ac feugiat sed. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Senectus et netus et malesuada fames ac turpis. Et ultrices neque ornare aenean euismod elementum. Elit at imperdiet dui accumsan sit.

Gravida rutrum quisque non tellus orci ac auctor. Quis enim lobortis scelerisque fermentum dui faucibus. Augue eget arcu dictum varius. Nulla porttitor massa id neque aliquam vestibulum morbi. Malesuada fames ac turpis egestas. Nibh cras pulvinar mattis nunc. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Sit amet cursus sit amet dictum sit amet. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Massa tempor nec feugiat nisl pretium fusce. In pellentesque massa placerat duis. Tortor posuere ac ut consequat semper viverra. Interdum velit euismod in pellentesque massa placerat duis ultricies. Suspendisse in est ante in nibh mauris cursus mattis. At augue eget arcu dictum. Ultrices gravida dictum fusce ut placerat orci nulla. Ipsum a arcu cursus vitae congue mauris. Sit amet dictum sit amet justo donec enim diam vulputate. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum.

Pellentesque habitant morbi tristique senectus. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Vel quam elementum pulvinar etiam non quam. At urna condimentum mattis pellentesque id nibh. Blandit turpis cursus in hac habitasse platea dictumst quisque. Donec pretium vulputate sapien nec. Integer enim neque volutpat ac. Egestas quis ipsum suspendisse ultrices gravida. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. In fermentum et sollicitudin ac orci phasellus egestas tellus. Justo nec ultrices dui sapien eget mi proin. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Aliquam ultrices sagittis orci a scelerisque purus semper. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Sit amet porttitor eget dolor morbi non. Bibendum at varius vel pharetra vel turpis nunc. Viverra justo nec ultrices dui sapien eget mi proin. Tortor consequat id porta nibh venenatis cras sed.

In tellus integer feugiat scelerisque varius morbi enim. Pharetra pharetra massa massa ultricies mi quis hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Cursus turpis massa tincidunt dui ut ornare lectus. Donec et odio pellentesque diam. Sed nisi lacus sed viverra. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Aliquam sem fringilla ut morbi tincidunt. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Aliquam malesuada bibendum arcu vitae elementum curabitur. Sed risus ultricies tristique nulla aliquet enim. Quisque non tellus orci ac auctor augue. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Sit amet dictum sit amet justo donec enim diam. Nibh venenatis cras sed felis. Nunc congue nisi vitae suscipit tellus.', '2021-01-14', 14, 1, 1),
       ('Article 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices dui sapien eget mi proin sed libero. Vitae tempus quam pellentesque nec. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Curabitur vitae nunc sed velit dignissim. Enim praesent elementum facilisis leo vel. In eu mi bibendum neque egestas congue quisque egestas diam. Vivamus at augue eget arcu. Nulla facilisi etiam dignissim diam quis enim. Id consectetur purus ut faucibus pulvinar elementum integer. Et molestie ac feugiat sed lectus vestibulum. Rhoncus dolor purus non enim. Eget gravida cum sociis natoque penatibus et magnis. Tincidunt tortor aliquam nulla facilisi cras fermentum. In aliquam sem fringilla ut morbi tincidunt augue. In massa tempor nec feugiat nisl.

Id neque aliquam vestibulum morbi. Varius morbi enim nunc faucibus a pellentesque. Dui sapien eget mi proin. Nisl nisi scelerisque eu ultrices vitae. Duis tristique sollicitudin nibh sit amet commodo nulla. Sem et tortor consequat id porta nibh venenatis cras. In hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida. Tempor orci eu lobortis elementum nibh tellus molestie. Scelerisque varius morbi enim nunc faucibus a pellentesque. Fringilla est ullamcorper eget nulla. Congue eu consequat ac felis donec et odio. Elit ut aliquam purus sit amet luctus venenatis lectus. Scelerisque in dictum non consectetur a erat.

Velit ut tortor pretium viverra suspendisse potenti nullam ac. Ornare arcu odio ut sem nulla. Varius sit amet mattis vulputate enim. Nec feugiat nisl pretium fusce id velit ut. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Quis auctor elit sed vulputate mi sit amet mauris. Eu augue ut lectus arcu. Condimentum vitae sapien pellentesque habitant morbi. Senectus et netus et malesuada fames ac turpis. Interdum velit laoreet id donec ultrices.

Varius duis at consectetur lorem. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Tellus mauris a diam maecenas sed enim ut sem. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Velit scelerisque in dictum non. Et egestas quis ipsum suspendisse ultrices gravida. Nibh sit amet commodo nulla facilisi. Turpis massa sed elementum tempus egestas sed sed. Leo in vitae turpis massa sed. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Netus et malesuada fames ac. Varius sit amet mattis vulputate enim. Bibendum neque egestas congue quisque egestas diam in.

Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Amet risus nullam eget felis eget nunc. Nisi est sit amet facilisis magna. Odio euismod lacinia at quis risus. Tortor vitae purus faucibus ornare suspendisse sed nisi. Ut ornare lectus sit amet est. Etiam erat velit scelerisque in dictum. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Viverra vitae congue eu consequat. In egestas erat imperdiet sed euismod nisi. Arcu ac tortor dignissim convallis aenean. Nisi scelerisque eu ultrices vitae.', '2023-02-24', 12, 2, 2),
       ('Article 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat vivamus at augue eget arcu dictum varius duis. Volutpat maecenas volutpat blandit aliquam etiam. Suspendisse in est ante in nibh. Lorem mollis aliquam ut porttitor leo. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Purus sit amet volutpat consequat. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Nibh sed pulvinar proin gravida hendrerit. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Aliquam nulla facilisi cras fermentum. Enim blandit volutpat maecenas volutpat blandit. Tellus orci ac auctor augue mauris augue neque gravida. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Tristique senectus et netus et malesuada fames ac turpis egestas. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in.

Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Suscipit adipiscing bibendum est ultricies integer. Neque sodales ut etiam sit amet nisl purus in mollis. Lacus sed turpis tincidunt id aliquet. Semper eget duis at tellus at urna condimentum. Eget nunc lobortis mattis aliquam faucibus purus. Diam in arcu cursus euismod quis viverra nibh. Tortor at auctor urna nunc id cursus. Facilisis gravida neque convallis a cras semper auctor neque vitae. Sem nulla pharetra diam sit amet nisl suscipit. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Augue ut lectus arcu bibendum at varius vel pharetra. Id eu nisl nunc mi ipsum faucibus vitae.

Mi sit amet mauris commodo quis imperdiet massa. Nisl rhoncus mattis rhoncus urna neque viverra justo. Netus et malesuada fames ac turpis. Leo in vitae turpis massa sed elementum tempus. Faucibus pulvinar elementum integer enim neque volutpat. Ut aliquam purus sit amet luctus venenatis lectus magna. Sed odio morbi quis commodo odio aenean sed. A scelerisque purus semper eget duis at tellus. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Nunc sed velit dignissim sodales ut eu sem integer. Turpis egestas sed tempus urna et pharetra. Sit amet risus nullam eget felis eget nunc lobortis. Nisl suscipit adipiscing bibendum est ultricies integer quis. Sem et tortor consequat id porta nibh venenatis. Arcu vitae elementum curabitur vitae nunc sed velit. Vitae et leo duis ut diam quam. Et ultrices neque ornare aenean euismod. Eu augue ut lectus arcu.

Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Risus in hendrerit gravida rutrum. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Massa vitae tortor condimentum lacinia quis vel. Sed risus pretium quam vulputate. Sed vulputate mi sit amet. Sed ullamcorper morbi tincidunt ornare massa. Quis varius quam quisque id diam. Feugiat sed lectus vestibulum mattis ullamcorper velit. Id velit ut tortor pretium viverra suspendisse potenti. Integer eget aliquet nibh praesent tristique magna. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Mattis pellentesque id nibh tortor id aliquet lectus proin. Aliquam ut porttitor leo a diam sollicitudin. Posuere lorem ipsum dolor sit amet consectetur adipiscing.

Lorem sed risus ultricies tristique nulla. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Posuere ac ut consequat semper viverra. Purus ut faucibus pulvinar elementum integer. Aliquam faucibus purus in massa. Iaculis nunc sed augue lacus viverra vitae. Mattis aliquam faucibus purus in massa tempor nec. Leo vel fringilla est ullamcorper eget nulla. Pretium vulputate sapien nec sagittis. Eros donec ac odio tempor. Ac tincidunt vitae semper quis lectus nulla at. Vulputate ut pharetra sit amet. Cursus in hac habitasse platea dictumst quisque. Sed viverra tellus in hac habitasse platea dictumst.', '2022-03-15', 56, 3, 3),
       ('Article 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed odio morbi quis commodo odio aenean sed adipiscing. Scelerisque mauris pellentesque pulvinar pellentesque habitant. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Porttitor rhoncus dolor purus non enim praesent. Neque sodales ut etiam sit amet nisl purus. Amet mauris commodo quis imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Tellus in hac habitasse platea. Etiam dignissim diam quis enim lobortis scelerisque.

Quis ipsum suspendisse ultrices gravida dictum fusce ut. Eu scelerisque felis imperdiet proin fermentum leo vel. Sed arcu non odio euismod lacinia at. Purus sit amet luctus venenatis. Mattis pellentesque id nibh tortor id aliquet lectus. Pellentesque id nibh tortor id aliquet. Id aliquet lectus proin nibh nisl. Arcu vitae elementum curabitur vitae nunc. Dictum varius duis at consectetur lorem. Scelerisque varius morbi enim nunc faucibus a. Vitae nunc sed velit dignissim sodales ut. Eget aliquet nibh praesent tristique. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Amet cursus sit amet dictum sit amet. At quis risus sed vulputate odio ut. Faucibus turpis in eu mi. Eget magna fermentum iaculis eu non diam phasellus. Ipsum a arcu cursus vitae. Convallis a cras semper auctor neque.

Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Eu mi bibendum neque egestas congue quisque egestas. Eget nunc scelerisque viverra mauris. Feugiat nisl pretium fusce id. Diam donec adipiscing tristique risus nec feugiat in fermentum. Pulvinar pellentesque habitant morbi tristique senectus. Ac orci phasellus egestas tellus. Quam elementum pulvinar etiam non quam. Scelerisque eu ultrices vitae auctor eu. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Justo nec ultrices dui sapien eget mi proin sed. Donec et odio pellentesque diam volutpat commodo sed. Augue lacus viverra vitae congue eu. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Pharetra pharetra massa massa ultricies mi. Sodales neque sodales ut etiam sit amet. Quis auctor elit sed vulputate. Non consectetur a erat nam at lectus urna. Quam nulla porttitor massa id neque aliquam vestibulum.

Aliquam id diam maecenas ultricies mi eget. Quisque sagittis purus sit amet. Vitae congue eu consequat ac felis donec et. At elementum eu facilisis sed odio morbi. Netus et malesuada fames ac turpis egestas. Senectus et netus et malesuada fames ac. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Leo integer malesuada nunc vel risus. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Aliquam purus sit amet luctus. Elementum sagittis vitae et leo duis ut. Turpis massa tincidunt dui ut ornare lectus. Faucibus purus in massa tempor nec feugiat nisl pretium. Aliquet nibh praesent tristique magna sit amet purus gravida quis.

Feugiat in fermentum posuere urna nec. Aliquam sem et tortor consequat id. Sagittis aliquam malesuada bibendum arcu vitae. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. At erat pellentesque adipiscing commodo elit at imperdiet dui. Congue quisque egestas diam in arcu cursus. Tincidunt eget nullam non nisi est sit. Pretium nibh ipsum consequat nisl. Quam nulla porttitor massa id. Non consectetur a erat nam. Massa sed elementum tempus egestas sed sed risus. A pellentesque sit amet porttitor eget dolor.', '2023-04-24', 28, 4, 4),
       ('Article 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Elit at imperdiet dui accumsan sit amet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Est lorem ipsum dolor sit amet. Arcu cursus vitae congue mauris rhoncus. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Morbi tristique senectus et netus et. Nec dui nunc mattis enim. Ut tellus elementum sagittis vitae et leo duis. Odio euismod lacinia at quis risus sed vulputate. Pellentesque eu tincidunt tortor aliquam nulla. Euismod lacinia at quis risus sed vulputate odio ut enim. Eu sem integer vitae justo eget magna fermentum iaculis eu. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. In massa tempor nec feugiat.

Est sit amet facilisis magna etiam. Libero justo laoreet sit amet cursus sit amet. Rhoncus est pellentesque elit ullamcorper. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Integer vitae justo eget magna fermentum iaculis eu non. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Commodo ullamcorper a lacus vestibulum. Auctor eu augue ut lectus arcu bibendum at varius vel. Massa ultricies mi quis hendrerit. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Sed arcu non odio euismod lacinia at quis risus. Ultricies mi eget mauris pharetra.

Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Cras fermentum odio eu feugiat pretium nibh. Venenatis cras sed felis eget velit aliquet sagittis. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Vitae aliquet nec ullamcorper sit amet. Facilisis mauris sit amet massa vitae. Proin nibh nisl condimentum id venenatis a condimentum. Diam quam nulla porttitor massa id neque aliquam. Fames ac turpis egestas integer eget aliquet. Tristique senectus et netus et malesuada fames ac. Ornare quam viverra orci sagittis. Bibendum enim facilisis gravida neque convallis a cras. Dolor sit amet consectetur adipiscing. Id venenatis a condimentum vitae. Quam quisque id diam vel. Semper risus in hendrerit gravida.

Blandit turpis cursus in hac habitasse platea dictumst. Consequat id porta nibh venenatis cras sed. Tempus quam pellentesque nec nam. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Vulputate odio ut enim blandit. In vitae turpis massa sed elementum. Egestas dui id ornare arcu odio ut sem nulla pharetra. Urna porttitor rhoncus dolor purus. Vel orci porta non pulvinar neque laoreet suspendisse. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Nisl vel pretium lectus quam. Scelerisque felis imperdiet proin fermentum. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Ornare arcu odio ut sem nulla pharetra diam sit amet. Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Leo urna molestie at elementum eu facilisis. Et tortor at risus viverra adipiscing at in tellus.

Aliquet eget sit amet tellus cras adipiscing enim eu. Amet nulla facilisi morbi tempus iaculis urna id. Sodales ut etiam sit amet nisl purus in mollis nunc. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Ante metus dictum at tempor commodo ullamcorper. In massa tempor nec feugiat nisl pretium. Quis imperdiet massa tincidunt nunc. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Eget nullam non nisi est sit amet facilisis magna etiam. Dignissim enim sit amet venenatis urna cursus eget nunc. Et sollicitudin ac orci phasellus egestas tellus rutrum. Et ligula ullamcorper malesuada proin libero nunc consequat. Nec nam aliquam sem et tortor consequat. Non sodales neque sodales ut etiam. Velit egestas dui id ornare arcu odio ut sem. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Adipiscing enim eu turpis egestas pretium. Lorem ipsum dolor sit amet consectetur adipiscing elit. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque.', '2023-05-04', 47, 5, 5),
       ('Article 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque purus semper eget duis at tellus. Facilisis sed odio morbi quis commodo odio. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Quis hendrerit dolor magna eget. Suscipit tellus mauris a diam. Nulla posuere sollicitudin aliquam ultrices sagittis. Suspendisse in est ante in nibh mauris cursus. Nisl nunc mi ipsum faucibus vitae. Ut tellus elementum sagittis vitae et leo duis ut. Dignissim convallis aenean et tortor at risus viverra adipiscing.

Diam ut venenatis tellus in. Egestas maecenas pharetra convallis posuere morbi leo urna. Urna et pharetra pharetra massa massa ultricies mi. Congue mauris rhoncus aenean vel elit. Aliquet enim tortor at auctor urna nunc id. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Non blandit massa enim nec dui nunc mattis. Bibendum ut tristique et egestas quis ipsum. Nec sagittis aliquam malesuada bibendum.

Nibh tellus molestie nunc non. Diam quam nulla porttitor massa id. Varius quam quisque id diam vel quam elementum pulvinar etiam. Magna etiam tempor orci eu lobortis elementum nibh. Quisque sagittis purus sit amet volutpat consequat. Malesuada bibendum arcu vitae elementum curabitur. Semper quis lectus nulla at volutpat diam. Turpis egestas pretium aenean pharetra. Dictumst quisque sagittis purus sit. At quis risus sed vulputate odio ut. Quisque id diam vel quam elementum pulvinar etiam non quam.

Pellentesque nec nam aliquam sem et tortor. Congue nisi vitae suscipit tellus mauris. Euismod lacinia at quis risus sed. Nisl nunc mi ipsum faucibus vitae. Velit euismod in pellentesque massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Auctor neque vitae tempus quam pellentesque. Volutpat diam ut venenatis tellus in metus vulputate. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Ut etiam sit amet nisl purus in mollis nunc. Aliquet enim tortor at auctor urna nunc id cursus. Amet volutpat consequat mauris nunc congue nisi vitae. Aliquam vestibulum morbi blandit cursus risus. Aliquet enim tortor at auctor urna. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Ac turpis egestas sed tempus urna et pharetra. Felis donec et odio pellentesque diam volutpat.

Lorem ipsum dolor sit amet consectetur adipiscing elit. Elementum integer enim neque volutpat ac. Sit amet nulla facilisi morbi tempus iaculis. Mattis rhoncus urna neque viverra justo nec ultrices dui. Posuere ac ut consequat semper. Mattis pellentesque id nibh tortor id aliquet lectus proin. Eu nisl nunc mi ipsum faucibus. Maecenas volutpat blandit aliquam etiam erat. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Tristique nulla aliquet enim tortor at auctor urna. At consectetur lorem donec massa. In hac habitasse platea dictumst quisque. Turpis nunc eget lorem dolor sed. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Arcu risus quis varius quam quisque. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Cursus mattis molestie a iaculis at erat. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit.', '2022-06-24', 189, 6, 6),
       ('Article 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod quis viverra nibh cras pulvinar mattis. Sit amet nisl purus in mollis nunc sed id. Amet facilisis magna etiam tempor orci eu. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Id semper risus in hendrerit. Sed cras ornare arcu dui vivamus. Velit scelerisque in dictum non consectetur. Eu mi bibendum neque egestas congue quisque egestas diam. Diam sit amet nisl suscipit adipiscing. Donec ac odio tempor orci. Morbi blandit cursus risus at ultrices mi tempus. Aliquet nec ullamcorper sit amet risus nullam. Quisque non tellus orci ac auctor augue. Rhoncus est pellentesque elit ullamcorper dignissim cras. Porttitor lacus luctus accumsan tortor. Auctor neque vitae tempus quam pellentesque. Mauris in aliquam sem fringilla ut morbi.

Dui sapien eget mi proin sed libero enim sed. Vitae congue eu consequat ac felis donec et odio pellentesque. In tellus integer feugiat scelerisque varius morbi. Tempus iaculis urna id volutpat. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Sit amet consectetur adipiscing elit. Cursus in hac habitasse platea dictumst quisque sagittis. Enim neque volutpat ac tincidunt vitae semper. Malesuada fames ac turpis egestas integer. Sem viverra aliquet eget sit. Libero id faucibus nisl tincidunt eget nullam non. Massa id neque aliquam vestibulum. Eros in cursus turpis massa tincidunt dui ut ornare. Nec ullamcorper sit amet risus nullam eget. Pulvinar neque laoreet suspendisse interdum consectetur libero id.

Tellus mauris a diam maecenas sed enim. Elementum eu facilisis sed odio morbi quis. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Urna cursus eget nunc scelerisque viverra mauris in. Sed libero enim sed faucibus turpis in eu. Eu consequat ac felis donec et odio pellentesque diam. Aenean euismod elementum nisi quis eleifend quam. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Quam vulputate dignissim suspendisse in est ante.

Est ultricies integer quis auctor elit sed vulputate. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Habitant morbi tristique senectus et netus et. Nec nam aliquam sem et tortor consequat id porta. Consequat mauris nunc congue nisi vitae suscipit. Porttitor massa id neque aliquam. Purus semper eget duis at tellus at. Convallis a cras semper auctor neque vitae tempus. Scelerisque viverra mauris in aliquam. A diam sollicitudin tempor id eu. Feugiat in ante metus dictum at tempor. Quam elementum pulvinar etiam non quam lacus. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Malesuada pellentesque elit eget gravida cum sociis. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Maecenas sed enim ut sem viverra aliquet eget. Diam quam nulla porttitor massa id neque. Non sodales neque sodales ut etiam sit amet. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.

Libero volutpat sed cras ornare arcu. Et malesuada fames ac turpis egestas sed tempus. Purus viverra accumsan in nisl. Enim neque volutpat ac tincidunt vitae semper quis. Et netus et malesuada fames ac turpis egestas. Quam vulputate dignissim suspendisse in est ante. Mauris in aliquam sem fringilla ut morbi tincidunt. Condimentum vitae sapien pellentesque habitant morbi tristique. Sed vulputate mi sit amet. Pellentesque dignissim enim sit amet.', '2023-07-24', 82, 7, 7),
       ('Article 8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque viverra mauris in aliquam sem. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Purus semper eget duis at tellus at urna condimentum. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Mi quis hendrerit dolor magna eget est. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet est placerat in egestas erat imperdiet. Neque sodales ut etiam sit amet nisl. Non curabitur gravida arcu ac. Aliquet enim tortor at auctor urna nunc id. A erat nam at lectus urna duis. Pharetra massa massa ultricies mi quis hendrerit dolor. Montes nascetur ridiculus mus mauris vitae ultricies. Faucibus scelerisque eleifend donec pretium vulputate. At in tellus integer feugiat. Venenatis a condimentum vitae sapien pellentesque habitant. Feugiat nisl pretium fusce id velit ut tortor pretium viverra.

Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Elit duis tristique sollicitudin nibh sit amet commodo. Dictum at tempor commodo ullamcorper a lacus. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Molestie at elementum eu facilisis sed. In eu mi bibendum neque egestas congue quisque egestas. Arcu dictum varius duis at consectetur lorem donec massa. Velit dignissim sodales ut eu sem integer. Commodo sed egestas egestas fringilla phasellus faucibus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed adipiscing diam donec adipiscing tristique risus. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Odio euismod lacinia at quis. Ultrices sagittis orci a scelerisque. Fermentum dui faucibus in ornare quam. Cras semper auctor neque vitae tempus quam pellentesque nec nam.

Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Sit amet est placerat in egestas erat. Elit sed vulputate mi sit. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Velit euismod in pellentesque massa placerat. Et odio pellentesque diam volutpat. Diam maecenas sed enim ut sem viverra aliquet eget. Arcu vitae elementum curabitur vitae nunc. Egestas congue quisque egestas diam in arcu cursus euismod. Et ultrices neque ornare aenean euismod elementum nisi. Vel facilisis volutpat est velit egestas dui. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing.

Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Ultricies leo integer malesuada nunc vel risus commodo viverra. Et ultrices neque ornare aenean euismod elementum nisi quis. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Bibendum est ultricies integer quis auctor. Viverra nam libero justo laoreet sit. Sed elementum tempus egestas sed sed risus pretium. Nunc aliquet bibendum enim facilisis. Turpis egestas pretium aenean pharetra magna.

Sapien et ligula ullamcorper malesuada proin libero. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Eu turpis egestas pretium aenean pharetra. Sit amet mattis vulputate enim nulla. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Mi quis hendrerit dolor magna eget est lorem. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Vel quam elementum pulvinar etiam non quam lacus suspendisse. Etiam tempor orci eu lobortis elementum. Eu consequat ac felis donec et odio pellentesque diam. Tortor posuere ac ut consequat semper. Ultricies lacus sed turpis tincidunt id aliquet risus. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Id porta nibh venenatis cras sed. Turpis egestas pretium aenean pharetra magna.', '2023-08-24', 153, 8, 8),
       ('Article 9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam donec adipiscing tristique risus. At augue eget arcu dictum varius duis at consectetur lorem. Congue nisi vitae suscipit tellus mauris a diam maecenas. Tellus id interdum velit laoreet id. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Dolor sed viverra ipsum nunc aliquet bibendum enim. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Tristique sollicitudin nibh sit amet commodo nulla. Enim diam vulputate ut pharetra sit.

Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Pellentesque dignissim enim sit amet venenatis urna cursus. Ac felis donec et odio. In vitae turpis massa sed. Pellentesque diam volutpat commodo sed. Integer vitae justo eget magna fermentum iaculis. Vitae auctor eu augue ut lectus arcu bibendum. Mollis nunc sed id semper. Tristique et egestas quis ipsum suspendisse. In hac habitasse platea dictumst vestibulum rhoncus. Eu consequat ac felis donec et. Felis eget nunc lobortis mattis. Pharetra massa massa ultricies mi quis hendrerit dolor magna.

Facilisis leo vel fringilla est ullamcorper eget nulla. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Risus quis varius quam quisque id diam vel quam. Donec adipiscing tristique risus nec. Nam libero justo laoreet sit amet cursus sit amet dictum. Blandit volutpat maecenas volutpat blandit. A diam maecenas sed enim ut sem viverra. Mi sit amet mauris commodo quis imperdiet. Leo integer malesuada nunc vel. Diam quam nulla porttitor massa id. Nisi porta lorem mollis aliquam ut porttitor leo a. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Pellentesque id nibh tortor id aliquet lectus proin nibh. Commodo nulla facilisi nullam vehicula ipsum a.

Nunc sed velit dignissim sodales ut. Nulla pellentesque dignissim enim sit. Aliquam etiam erat velit scelerisque in dictum non consectetur. Lacus sed turpis tincidunt id aliquet risus feugiat in. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Enim diam vulputate ut pharetra sit. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Consequat semper viverra nam libero justo. Ac tortor dignissim convallis aenean et tortor at. Velit egestas dui id ornare. Aliquam malesuada bibendum arcu vitae. Vulputate mi sit amet mauris commodo quis imperdiet.

Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sed viverra tellus in hac habitasse platea. Orci ac auctor augue mauris augue neque. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Nibh praesent tristique magna sit amet purus gravida quis blandit. Justo nec ultrices dui sapien. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Ut diam quam nulla porttitor massa. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Tempor id eu nisl nunc. Et pharetra pharetra massa massa. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Nam at lectus urna duis convallis convallis tellus. Netus et malesuada fames ac turpis egestas integer eget aliquet. Ultrices in iaculis nunc sed augue.', '2020-09-24', 54, 9, 9),
       ('Article 10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet sit amet cursus sit. Est ante in nibh mauris cursus mattis. Enim facilisis gravida neque convallis a cras semper. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Tempus imperdiet nulla malesuada pellentesque. Nunc consequat interdum varius sit amet. Duis ultricies lacus sed turpis tincidunt id. Mauris rhoncus aenean vel elit. Libero id faucibus nisl tincidunt. Elementum curabitur vitae nunc sed velit.

Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Arcu cursus euismod quis viverra nibh. Posuere morbi leo urna molestie at elementum eu facilisis sed. Sapien et ligula ullamcorper malesuada proin libero. Tincidunt id aliquet risus feugiat in ante. Eget mi proin sed libero enim sed faucibus turpis in. Et netus et malesuada fames ac. Elementum facilisis leo vel fringilla. In iaculis nunc sed augue. Non quam lacus suspendisse faucibus. Sit amet facilisis magna etiam tempor orci eu lobortis. Consequat semper viverra nam libero justo laoreet sit. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Nunc non blandit massa enim nec dui. Nullam ac tortor vitae purus. Viverra suspendisse potenti nullam ac tortor. Arcu ac tortor dignissim convallis.

Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Orci porta non pulvinar neque laoreet suspendisse interdum. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Amet mattis vulputate enim nulla aliquet porttitor. A lacus vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non. Amet cursus sit amet dictum sit amet. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Faucibus purus in massa tempor nec feugiat nisl. Quis hendrerit dolor magna eget est. Sed tempus urna et pharetra. Mattis rhoncus urna neque viverra justo nec ultrices dui. Lectus sit amet est placerat in egestas erat imperdiet sed. Interdum varius sit amet mattis. Mollis nunc sed id semper. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum.

Varius sit amet mattis vulputate. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Vitae justo eget magna fermentum iaculis eu non diam. Purus gravida quis blandit turpis cursus in hac habitasse platea. Laoreet sit amet cursus sit. Penatibus et magnis dis parturient montes nascetur. Pulvinar proin gravida hendrerit lectus. Eget magna fermentum iaculis eu non diam phasellus. Amet justo donec enim diam vulputate. Massa sed elementum tempus egestas sed sed. Euismod lacinia at quis risus sed vulputate odio. Penatibus et magnis dis parturient montes. Felis bibendum ut tristique et egestas quis ipsum. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Netus et malesuada fames ac. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Ut porttitor leo a diam sollicitudin.

Sit amet mauris commodo quis. Blandit massa enim nec dui nunc mattis enim ut. Eros in cursus turpis massa tincidunt. Sed risus pretium quam vulputate dignissim suspendisse. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Tincidunt eget nullam non nisi est sit amet facilisis magna. In ante metus dictum at tempor commodo ullamcorper. In hac habitasse platea dictumst quisque. Varius vel pharetra vel turpis nunc eget lorem. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. Sem et tortor consequat id porta nibh venenatis cras. Hac habitasse platea dictumst quisque sagittis purus sit amet. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Metus aliquam eleifend mi in nulla. Feugiat nisl pretium fusce id velit ut tortor. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Non enim praesent elementum facilisis leo vel fringilla est.', '2023-10-24', 121, 10, 10);

INSERT INTO comment (content, datetime, author_id, news_id)
VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut tellus elementum sagittis vitae et leo. Justo laoreet sit amet cursus sit amet dictum sit amet. Tortor condimentum lacinia quis vel eros. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Ac feugiat sed lectus vestibulum mattis ullamcorper. Duis at consectetur lorem donec massa sapien faucibus. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Massa tempor nec feugiat nisl pretium. Eget nunc lobortis mattis aliquam faucibus. In mollis nunc sed id semper risus. Et malesuada fames ac turpis. Placerat duis ultricies lacus sed turpis tincidunt id aliquet risus.', '2023-04-24', 3, 1),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci porta non pulvinar neque. Sagittis orci a scelerisque purus semper eget duis at tellus. Neque egestas congue quisque egestas diam in. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Mauris in aliquam sem fringilla ut morbi. Neque viverra justo nec ultrices dui sapien. Adipiscing at in tellus integer. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Neque vitae tempus quam pellentesque. Egestas diam in arcu cursus euismod quis viverra nibh. Natoque penatibus et magnis dis. Dui nunc mattis enim ut tellus elementum sagittis. Curabitur vitae nunc sed velit dignissim sodales.', '2021-05-14', 5, 2),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet risus nullam eget felis eget nunc. Auctor urna nunc id cursus. Accumsan sit amet nulla facilisi morbi tempus iaculis. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Orci sagittis eu volutpat odio facilisis mauris sit. Quis eleifend quam adipiscing vitae. Arcu odio ut sem nulla pharetra diam sit amet nisl. Justo donec enim diam vulputate ut pharetra. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Dolor sit amet consectetur adipiscing elit pellentesque. Commodo odio aenean sed adipiscing diam. Vivamus at augue eget arcu dictum varius duis at. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Posuere ac ut consequat semper viverra. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut.', '2022-11-30', 7, 3),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque egestas. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Faucibus in ornare quam viverra orci. At urna condimentum mattis pellentesque id nibh tortor id. At risus viverra adipiscing at. Id volutpat lacus laoreet non curabitur gravida arcu ac. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Adipiscing elit duis tristique sollicitudin nibh sit amet. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Pellentesque diam volutpat commodo sed egestas. Quis blandit turpis cursus in.', '2021-02-05', 9, 4),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat sed lectus vestibulum mattis ullamcorper. Bibendum est ultricies integer quis auctor elit sed. Quam viverra orci sagittis eu volutpat odio facilisis. Turpis egestas maecenas pharetra convallis. Eu facilisis sed odio morbi quis commodo odio aenean sed. Ultricies leo integer malesuada nunc vel. Tempus imperdiet nulla malesuada pellentesque. Mattis rhoncus urna neque viverra justo nec ultrices dui. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Mauris augue neque gravida in fermentum.', '2020-10-27', 11, 5),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac. Viverra ipsum nunc aliquet bibendum enim facilisis. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Quisque id diam vel quam elementum. Vulputate ut pharetra sit amet aliquam id. Dictum sit amet justo donec enim diam vulputate. Eget magna fermentum iaculis eu. At lectus urna duis convallis convallis tellus. Est pellentesque elit ullamcorper dignissim.', '2022-08-12', 13, 6),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tristique senectus et netus et malesuada. Orci eu lobortis elementum nibh tellus molestie nunc non. Imperdiet sed euismod nisi porta lorem mollis aliquam. Eget arcu dictum varius duis at. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Auctor urna nunc id cursus metus. Posuere ac ut consequat semper viverra nam libero justo. Urna nec tincidunt praesent semper feugiat nibh. Sem nulla pharetra diam sit. Sed turpis tincidunt id aliquet. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl.', '2021-06-19', 15, 7),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Odio aenean sed adipiscing diam donec. Lorem mollis aliquam ut porttitor leo. Bibendum at varius vel pharetra vel turpis nunc eget lorem. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Donec et odio pellentesque diam volutpat commodo. Sed vulputate odio ut enim. Enim blandit volutpat maecenas volutpat. Felis bibendum ut tristique et. Nibh cras pulvinar mattis nunc sed. Pharetra sit amet aliquam id diam maecenas ultricies.', '2021-09-21', 17, 8),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales. Integer quis auctor elit sed. Phasellus egestas tellus rutrum tellus pellentesque. Posuere morbi leo urna molestie at. Integer eget aliquet nibh praesent tristique magna sit amet purus. Tristique senectus et netus et malesuada fames ac turpis egestas. In aliquam sem fringilla ut morbi tincidunt. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Sagittis eu volutpat odio facilisis mauris sit amet. Ornare arcu odio ut sem. A cras semper auctor neque vitae tempus. Porta nibh venenatis cras sed.', '2023-01-04', 18, 9),
       ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Quisque id diam vel quam. Rhoncus urna neque viverra justo nec. Ullamcorper velit sed ullamcorper morbi. Sed augue lacus viverra vitae congue eu consequat ac felis. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Elit pellentesque habitant morbi tristique senectus et. Iaculis at erat pellentesque adipiscing commodo elit at. Eget duis at tellus at urna condimentum mattis. Faucibus nisl tincidunt eget nullam non nisi est sit. Faucibus et molestie ac feugiat sed lectus. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Maecenas volutpat blandit aliquam etiam. Auctor elit sed vulputate mi sit amet mauris commodo. Tincidunt id aliquet risus feugiat in ante.', '2021-05-29', 21, 10)